### PR TITLE
feat: bump k8s version in integration tests to 1.22

### PR DESCRIPTION
**Pull request by ca-scribner**

### CODE REVIEW

**Comment by ca-scribner** [comment]
I think integration tests here will fail until #14 is merged.  After that, reruning these tests should be :heavy_check_mark:

**Review by DnPlas — APPROVED** [review]
LGTM, do you want to rebase your branch to catch all of what #14 introduced?

**Comment by ca-scribner** [comment]
Interestingly, this "passed" CI even though the charm actually failed.  I think I should debug that first

**Comment by ca-scribner** [comment]
Waiting on the bugs in #17 before we can resolve this

**Comment by ca-scribner** [comment]
Actually no, #17 is not really needed here.

**Pull request merged**
